packages:
  - packages/*
  - playground
catalog:
  "@antfu/eslint-config": ^3.12.1
  "@antfu/ni": ^0.23.2
  "@atlaskit/pragmatic-drag-and-drop": ^1.4.0
  "@atlaskit/pragmatic-drag-and-drop-hitbox": ^1.0.3
  "@ctrl/tinycolor": ^4.1.0
  "@iconify/tailwind": ^1.2.0
  "@iconify/vue": ^4.2.0
  "@intlify/unplugin-vue-i18n": ^6.0.2
  "@manypkg/get-packages": ^2.2.2
  "@radix-icons/vue": ^1.0.0
  "@rollup/plugin-commonjs": ^28.0.2
  "@rollup/plugin-node-resolve": ^16.0.0
  "@tailwindcss/typography": ^0.5.15
  "@types/dom-view-transitions": ^1.0.5
  "@types/eslint-plugin-tailwindcss": ^3.17.0
  "@types/lodash-es": ^4.17.12
  "@types/node": ^22.10.2
  "@unhead/vue": ^1.11.14
  "@vitejs/plugin-vue": ^5.2.1
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "@vueuse/core": ^12.2.0
  autoprefixer: ^10.4.20
  bumpp: ^9.9.2
  cac: ^6.7.14
  chalk: ^5.4.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cross-env: ^7.0.3
  cspell: ^8.17.1
  cssnano: ^7.0.6
  eslint: ^9.17.0
  eslint-flat-config-utils: ^0.4.0
  eslint-plugin-tailwindcss: ^3.17.5
  esno: ^4.8.0
  execa: ^9.5.2
  find-up: ^7.0.0
  lint-staged: ^15.2.11
  local-pkg: ^0.5.1
  lodash-es: ^4.17.21
  lucide-vue-next: ^0.469.0
  ora: ^8.1.1
  pkg-types: ^1.2.1
  postcss: ^8.4.49
  postcss-import: ^16.1.0
  postcss-nested: ^7.0.2
  postcss-preset-env: ^10.1.2
  radix-vue: ^1.9.11
  rimraf: ^6.0.1
  rollup: ^4.29.1
  rollup-plugin-typescript2: ^0.36.0
  rollup-plugin-visualizer: ^5.12.0
  shadcn-vue: ^0.11.3
  simple-git-hooks: ^2.11.1
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  taze: ^0.18.0
  tsup: ^8.3.5
  turbo: ^2.3.3
  typescript: ^5.7.2
  unbuild: ^2.0.0
  unplugin-auto-import: ^0.19.0
  unplugin-vue-components: ^0.28.0
  unplugin-vue-router: ^0.10.9
  vite: ^6.0.5
  vite-plugin-dts: ^4.4.0
  vite-plugin-html: ^3.2.2
  vite-plugin-lib-inject-css: ^2.1.1
  vite-plugin-vue-devtools: ^7.6.8
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-tsc: ^2.2.0
